import { DiffEditor } from "@monaco-editor/react";
import { useEffect, useState } from "react";
import type { ContextTrayItem } from "../../shared/context-tray";
import type { DocumentationUpdateContext, ValidatedDocumentationEdit } from "../../shared/documentation-update";
import MarkdownPreview from "./MarkdownPreview";

export interface DocumentationPreparation { context: DocumentationUpdateContext; availableContext: ContextTrayItem[]; userRequest: string; busy: boolean; error?: string }
export interface DocumentationReview { context: DocumentationUpdateContext; validated: ValidatedDocumentationEdit; busy: boolean; staleMessage?: string }
export type DocumentationUpdateView = { stage: "prepare"; value: DocumentationPreparation } | { stage: "review"; value: DocumentationReview } | { stage: "applied"; path: string; relationshipId: string };

interface Props { view: DocumentationUpdateView; theme: string; fontSize: number; onCancel: () => void; onGenerate: (request: string, selectedIds: string[]) => void; onEdit: (replacement: string) => void; onAccept: () => void; onRegenerate: () => void; onRefresh: () => void; onCopy: () => void; onOpenCode: () => void; onOpenDocument: () => void; onUndo: () => void; onPreview: () => void; onRecheck: () => void; onGitDiff: () => void; onAddContext: () => void }

export default function DocumentationUpdateWorkspace(props: Props) {
  const [showContext, setShowContext] = useState(false); const [request, setRequest] = useState(props.view.stage === "prepare" ? props.view.value.userRequest : ""); const [selected, setSelected] = useState<string[]>([]); const [rendered, setRendered] = useState(false);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); props.onCancel(); } }; window.addEventListener("keydown", close, { capture: true }); return () => window.removeEventListener("keydown", close, { capture: true }); }, [props.onCancel]);
  if (props.view.stage === "applied") return <div className="documentation-update-backdrop"><section className="documentation-update-dialog applied" role="dialog" aria-modal="true"><h2>Documentation update applied</h2><p>The Markdown file was saved after checkpoint and stale-content validation. No tests, commands, or Git actions ran.</p><div className="documentation-update-actions"><button onClick={props.onPreview}>Preview Updated Documentation</button><button onClick={props.onRecheck}>Recheck Documentation Relationship</button><button onClick={props.onGitDiff}>Open Git Diff</button><button onClick={props.onAddContext}>Add Relevant Files to Context Tray</button><button onClick={props.onUndo}>Undo Documentation Update</button><button onClick={props.onCancel}>Close</button></div></section></div>;
  const context = props.view.value.context;
  if (props.view.stage === "prepare") return <div className="documentation-update-backdrop"><section className="documentation-update-dialog" role="dialog" aria-modal="true" aria-labelledby="documentation-preparation-title">
    <header><div><h2 id="documentation-preparation-title">Prepare Documentation Update</h2><p>Review exactly what may be sent before generating any draft.</p></div><button onClick={props.onCancel}>×</button></header>
    <div className="documentation-update-body"><dl><dt>Changed code</dt><dd>{context.codePath}</dd><dt>Affected documentation</dt><dd>{context.documentationPath}</dd><dt>Relationship</dt><dd>{context.relationshipType.replaceAll("_", " ")} · {context.confidence}</dd><dt>Evidence</dt><dd>{context.evidence}</dd><dt>Changed code summary</dt><dd>{context.reference}</dd><dt>Relevant section</dt><dd>{context.affectedHeading || "Document end / missing section"}</dd><dt>Context size</dt><dd>{(context.codeExcerpt.length + context.sectionText.length + (context.projectRules?.length ?? 0)).toLocaleString()} characters before optional items</dd><dt>Privacy</dt><dd>{context.redacted ? "Potential secrets were redacted; generation is blocked until refreshed safely." : "Secret scan passed; relative paths only."}</dd></dl>
      <label className="documentation-request"><span>Explicit update request</span><textarea value={request} maxLength={1_000} onChange={(event) => setRequest(event.target.value)} /></label>
      {props.view.value.availableContext.length > 0 && <fieldset><legend>Optional Context Tray items — select explicitly</legend>{props.view.value.availableContext.map((item) => <label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))} />{item.title}{item.webSource ? ` — external web source: ${item.webSource.sourceUrl}` : ""}</label>)}</fieldset>}
      {showContext && <div className="documentation-context-review"><h3>Code evidence</h3><pre>{context.codeExcerpt}</pre><h3>Markdown section</h3><pre>{context.sectionText || "A new section may be inserted."}</pre>{context.projectRules && <><h3>Project rules</h3><pre>{context.projectRules}</pre></>}</div>}
      {props.view.value.error && <p className="context-preview-warning" role="alert">{props.view.value.error}</p>}
    </div><footer><span>Nothing is sent until Generate Draft.</span><div><button onClick={() => setShowContext((value) => !value)}>Review Context</button><button className="primary" disabled={props.view.value.busy || context.redacted || !request.trim()} onClick={() => props.onGenerate(request.trim(), selected)}>{props.view.value.busy ? "Generating…" : "Generate Draft"}</button><button onClick={props.onCancel}>Cancel</button></div></footer>
  </section></div>;
  const review = props.view.value;
  return <div className="documentation-update-backdrop"><section className="documentation-update-dialog review" role="dialog" aria-modal="true"><header><div><h2>Review Documentation Draft</h2><p>{review.validated.edit.targetRelativePath} · {review.validated.edit.affectedHeading || "new section"}</p></div><button onClick={props.onCancel}>×</button></header>
    <div className="documentation-review-meta"><p>{review.validated.edit.explanation}</p><p>{review.validated.edit.reason}</p><span>+{review.validated.addedLines} / −{review.validated.deletedLines} lines · evidence {review.context.relationshipId}</span>{review.validated.edit.warnings.map((warning) => <strong key={warning}>{warning}</strong>)}{review.validated.edit.verificationNotes.map((note) => <em key={note}>{note}</em>)}{review.staleMessage && <strong className="stale">{review.staleMessage}</strong>}</div>
    <div className="documentation-review-tabs"><button className={!rendered ? "active" : ""} onClick={() => setRendered(false)}>Markdown Diff</button><button className={rendered ? "active" : ""} onClick={() => setRendered(true)}>Rendered Preview</button></div>
    {rendered ? <MarkdownPreview source={review.validated.proposedContent} /> : <DiffEditor original={review.context.documentationContent} modified={review.validated.proposedContent} language="markdown" theme={props.theme} options={{ readOnly: true, originalEditable: false, automaticLayout: true, fontSize: props.fontSize, minimap: { enabled: false } }} />}
    <label className="documentation-proposed-edit"><span>Edit proposed Markdown section</span><textarea value={review.validated.edit.replacementMarkdown} onChange={(event) => props.onEdit(event.target.value)} /></label>
    <footer><div><button onClick={props.onOpenCode}>Open Code Evidence</button><button onClick={props.onOpenDocument}>Open Original Document</button><button onClick={props.onCopy}>Copy Draft</button>{review.staleMessage && <button onClick={props.onRefresh}>Refresh Context</button>}<button onClick={props.onRegenerate}>Regenerate</button><button onClick={props.onCancel}>Reject</button><button className="primary" disabled={review.busy || Boolean(review.staleMessage)} onClick={props.onAccept}>{review.busy ? "Applying…" : "Accept Documentation Update"}</button></div></footer>
  </section></div>;
}
