import { DiffEditor } from "@monaco-editor/react";
import type { LocalSettings } from "../../shared/settings";
import { lineDiffStats, type MultiFileApplyResult, type MultiFileChangeSet, type MultiFilePlan } from "../../shared/multi-file-change";
import { monacoLanguageForFile } from "../../shared/languages";

export function MultiFilePlanReview({ plan, busy, error, onApprove, onEdit, onCancel }: { plan: MultiFilePlan; busy: boolean; error: string | null; onApprove: () => void; onEdit: () => void; onCancel: () => void }) {
  return <section className="multi-file-plan" aria-label="Multi-file implementation plan">
    <header><div><strong>Step 1 — Review Implementation Plan</strong><span>No files are modified during planning.</span></div><div><button onClick={onEdit}>Edit Request</button><button onClick={onCancel}>Cancel</button><button className="primary" disabled={busy} onClick={onApprove}>{busy ? "Preparing…" : "Approve Plan"}</button></div></header>
    <div className="multi-file-plan-body"><h2>{plan.summary}</h2>{error && <p className="multi-file-error" role="alert">{error}</p>}<div className="plan-columns"><section><h3>Existing files to update</h3>{plan.files.filter((file) => file.operation === "update").map((file) => <article key={file.relativePath}><code>{file.relativePath}</code><p>{file.reason}</p></article>)}{!plan.files.some((file) => file.operation === "update") && <p>None</p>}</section><section><h3>New files to create</h3>{plan.files.filter((file) => file.operation === "create").map((file) => <article key={file.relativePath}><code>{file.relativePath}</code><p>{file.reason}</p></article>)}{!plan.files.some((file) => file.operation === "create") && <p>None</p>}</section></div><section><h3>Risks</h3><ul>{plan.risks.map((risk) => <li key={risk}>{risk}</li>)}</ul></section><section><h3>Suggested verification</h3><ul>{plan.verificationSuggestions.map((item) => <li key={item}><code>{item}</code></li>)}</ul></section><p className="locked-safety">All files are required as one change set. Plan approval and later diff approval cannot be disabled.</p></div>
  </section>;
}

export function MultiFileChangeReview({ changeSet, activeIndex, settings, theme, applying, conflict, onSelect, onApprove, onReject, onRegenerate }: { changeSet: MultiFileChangeSet; activeIndex: number; settings: LocalSettings["editor"]; theme: "vs" | "vs-dark"; applying: boolean; conflict: string | null; onSelect: (index: number) => void; onApprove: () => void; onReject: () => void; onRegenerate: () => void }) {
  const active = changeSet.changes[activeIndex] ?? changeSet.changes[0]; const original = active.operation === "update" ? active.originalContent : ""; const stats = lineDiffStats(original, active.proposedContent);
  return <section className="multi-file-review" aria-label="Multi-file change-set review"><header><div><strong>Step 2 — Review Complete Change Set</strong><span>{changeSet.summary}</span></div><div><button onClick={onRegenerate}>Regenerate Entire Set</button><button onClick={onReject}>Reject Entire Set</button><button className="primary" disabled={applying || Boolean(conflict)} onClick={onApprove}>{applying ? "Preflight and apply…" : "Approve Entire Change Set"}</button></div></header><div className="multi-file-review-body"><aside><strong>{changeSet.changes.length} affected files</strong>{changeSet.changes.map((change, index) => { const itemStats = lineDiffStats(change.operation === "update" ? change.originalContent : "", change.proposedContent); return <button className={index === activeIndex ? "active" : ""} key={change.relativePath} onClick={() => onSelect(index)}><span>{change.operation === "create" ? "NEW" : "UPDATE"}</span><code>{change.relativePath}</code><small>+{itemStats.added} −{itemStats.deleted}</small></button>; })}</aside><main><div className="multi-file-meta"><strong>{active.relativePath}</strong><span>{active.operation} · +{stats.added} −{stats.deleted}</span><p>{active.explanation}</p>{changeSet.warnings.map((warning) => <em key={warning}>{warning}</em>)}{conflict && <b role="alert">{conflict}</b>}</div><div className="observer-review-labels"><span>{active.operation === "create" ? "Empty original" : "Original"}</span><span>Proposed — not applied</span></div><DiffEditor original={original} modified={active.proposedContent} language={monacoLanguageForFile(active.relativePath)} theme={theme} options={{ readOnly: true, originalEditable: false, automaticLayout: true, renderSideBySide: true, fontSize: settings.fontSize, wordWrap: settings.wordWrap ? "on" : "off", minimap: { enabled: false } }} /></main></div><footer><strong>Verification suggestions</strong>{changeSet.verificationSuggestions.map((item) => <code key={item}>{item}</code>)}<span>Optional-file exclusion is unavailable because dependency consistency cannot be proven safely.</span></footer></section>;
}

export function MultiFileAppliedSummary({ changeSet, result, undoing, onUndo, onRunVerification, onOpenTerminal, onSkip }: { changeSet: MultiFileChangeSet; result: MultiFileApplyResult; undoing: boolean; onUndo: () => void; onRunVerification: () => void; onOpenTerminal: () => void; onSkip: () => void }) {
  return <section className="multi-file-applied" aria-label="Multi-file change applied"><div><span aria-hidden="true">✓</span><h2>Multi-file change applied</h2><p>{changeSet.summary}</p><strong>{result.files.length} files · +{result.addedLines} −{result.deletedLines}</strong></div><section><h3>Suggested verification commands</h3>{changeSet.verificationSuggestions.length ? changeSet.verificationSuggestions.map((item) => <code key={item}>{item}</code>) : <p>No verification command was suggested.</p>}<p>Nothing runs unless you explicitly choose it.</p></section><div className="applied-actions"><button onClick={onUndo} disabled={undoing}>{undoing ? "Checking rollback…" : "Undo Multi-File Change"}</button><button onClick={onOpenTerminal}>Open Terminal</button><button onClick={onSkip}>Skip Verification</button><button className="primary" onClick={onRunVerification} disabled={!changeSet.verificationSuggestions.length}>Run Suggested Verification</button></div></section>;
}
