import { useCallback, useEffect, useMemo, useState } from "react";
import { ASSIST_PRESETS, INSIGHT_DETECTORS, recommendTuning, type AssistPreset, type InsightDetectorType, type ObserverInsightsReport } from "../../shared/proactive-insights";
import type { LocalSettings } from "../../shared/settings";

interface Props { local: LocalSettings; onChange: (settings: LocalSettings) => void; onSave: (settings: LocalSettings) => Promise<string | null> }
const detectorLabel: Record<InsightDetectorType, string> = { persistent_diagnostic: "Persistent diagnostic", failed_run: "Failed run", failed_test: "Failed test", failed_build: "Failed build", repeated_objective_failure: "Repeated objective failure" };
const percent = (value: number | null) => value === null ? "No responses" : `${Math.round(value * 100)}%`;
const duration = (value: number | null) => value === null ? "—" : value < 60_000 ? `${Math.round(value / 1_000)}s` : `${Math.round(value / 60_000)}m`;

export default function ObserverInsightsSettings({ local, onChange, onSave }: Props) {
  const [report, setReport] = useState<ObserverInsightsReport | null>(null);
  const [status, setStatus] = useState<string | null>(null);
  const [consent, setConsent] = useState(false);
  const [participantId, setParticipantId] = useState(() => `participant-${crypto.randomUUID().slice(0, 8)}`);
  const query = useMemo(() => ({ retentionDays: local.proactiveRetentionDays, metricsCollectionEnabled: local.proactiveMetricsCollection, mutedErrors: local.proactiveMutedErrors.length, mutedFiles: local.proactiveMutedFiles.length, mutedProjects: local.proactiveMutedProjects.length }), [local.proactiveMetricsCollection, local.proactiveMutedErrors.length, local.proactiveMutedFiles.length, local.proactiveMutedProjects.length, local.proactiveRetentionDays]);
  const refresh = useCallback(async () => { const result = await window.observerInsights.report(query); if (result.ok) setReport(result.value); else setStatus(result.error); }, [query]);
  useEffect(() => { void refresh(); }, [refresh]);
  const recommendation = report ? recommendTuning(report, local.proactiveDismissedRecommendations) : null;

  const applyPreset = (preset: AssistPreset) => {
    const value = ASSIST_PRESETS[preset]; const cooldowns = { persistent_diagnostic: value.cooldownMinutes, failed_run: value.cooldownMinutes, failed_test: value.cooldownMinutes, failed_build: value.cooldownMinutes }; const caps = { persistent_diagnostic: value.maximumPerHour, failed_run: value.maximumPerHour, failed_test: value.maximumPerHour, failed_build: value.maximumPerHour };
    onChange({ ...local, proactivePreset: preset, proactiveDiagnosticCycles: value.diagnosticCycles, proactiveFailedRunOccurrences: value.failedRunOccurrences, proactiveCooldownMinutes: value.cooldownMinutes, proactiveMaximumNudgesPerHour: value.maximumPerHour, proactiveDetectorCooldownMinutes: cooldowns, proactiveDetectorMaximumPerHour: caps });
  };
  const detectorEnabled = (detector: InsightDetectorType) => detector === "persistent_diagnostic" ? local.proactivePersistentDiagnostics : detector === "failed_run" ? local.proactiveFailedRuns : detector === "failed_test" ? local.proactiveFailedTests : detector === "failed_build" ? local.proactiveFailedBuilds : true;
  const setDetectorEnabled = (detector: InsightDetectorType, enabled: boolean) => onChange(detector === "persistent_diagnostic" ? { ...local, proactivePersistentDiagnostics: enabled } : detector === "failed_run" ? { ...local, proactiveFailedRuns: enabled } : detector === "failed_test" ? { ...local, proactiveFailedTests: enabled } : detector === "failed_build" ? { ...local, proactiveFailedBuilds: enabled } : local);
  const setDetectorNumber = (detector: Exclude<InsightDetectorType, "repeated_objective_failure">, field: "cooldown" | "maximum", value: number) => onChange(field === "cooldown" ? { ...local, proactiveDetectorCooldownMinutes: { ...local.proactiveDetectorCooldownMinutes, [detector]: value } } : { ...local, proactiveDetectorMaximumPerHour: { ...local.proactiveDetectorMaximumPerHour, [detector]: value } });
  const startEvaluation = async () => { if (!consent || !local.proactiveMetricsCollection) { setStatus("Enable local metrics collection before starting evaluation."); return; } const result = await window.observerInsights.session({ action: "start", participantId, preset: local.proactivePreset, timestamp: Date.now() }); setStatus(result.ok ? "FYP evaluation session started locally." : result.error); if (result.ok) { setConsent(false); await refresh(); } };
  const stopEvaluation = async () => { const result = await window.observerInsights.session({ action: "stop", timestamp: Date.now() }); setStatus(result.ok ? "Evaluation stopped. Data remains local until you export or clear it." : result.error); await refresh(); };
  const clearData = async () => { if (!window.confirm("Clear all local Observer insights and evaluation sessions? This cannot be undone.")) return; const result = await window.observerInsights.clear(); setStatus(result.ok ? "Observer insights data cleared." : result.error); await refresh(); };
  const exportData = async (format: "json" | "csv") => { const result = await window.observerInsights.export({ ...query, format }); setStatus(result.ok ? `Exported ${result.value.fileName}.` : result.error); };

  return <div className="observer-insights-settings">
    <h3>Observer Insights</h3><p>Privacy-safe local evaluation metadata only. No analytics leave this device automatically, and cloud sync is locked Off.</p>
    <div className="settings-actions"><label><input type="checkbox" checked={local.proactiveMetricsCollection} onChange={(event) => onChange({ ...local, proactiveMetricsCollection: event.target.checked })} /> Collect local aggregate metrics</label><label><input type="checkbox" checked={local.proactiveFeedbackPrompts} onChange={(event) => onChange({ ...local, proactiveFeedbackPrompts: event.target.checked })} /> Ask optional usefulness question</label></div>
    <label className="setting-row"><span>Local retention period (days)</span><input type="number" min="7" max="365" value={local.proactiveRetentionDays} onChange={(event) => onChange({ ...local, proactiveRetentionDays: Number(event.target.value) })} /></label>
    <button className="primary" onClick={() => void onSave(local).then((error) => setStatus(error ?? "Insights settings saved locally."))}>Save Insights settings</button>

    <h4>Sensitivity preset</h4><div className="insight-presets">{(["low", "balanced", "high"] as const).map((id) => <button key={id} className={local.proactivePreset === id ? "active" : ""} onClick={() => applyPreset(id)}><strong>{ASSIST_PRESETS[id].label}{id === "balanced" ? " · Recommended" : ""}</strong><span>{ASSIST_PRESETS[id].description}</span></button>)}</div><button onClick={() => applyPreset("balanced")}>Reset to Balanced</button>

    <details open><summary>Advanced detector controls and actual thresholds</summary><div className="detector-controls">{(["persistent_diagnostic", "failed_run", "failed_test", "failed_build"] as const).map((detector) => <section key={detector}><strong>{detectorLabel[detector]}</strong><label><input type="checkbox" checked={detectorEnabled(detector)} onChange={(event) => setDetectorEnabled(detector, event.target.checked)} /> Enabled</label><label>Threshold <input type="number" min={detector === "persistent_diagnostic" ? 2 : 1} max={detector === "persistent_diagnostic" ? 5 : detector === "failed_run" ? 3 : 1} disabled={detector === "failed_test" || detector === "failed_build"} value={detector === "persistent_diagnostic" ? local.proactiveDiagnosticCycles : detector === "failed_run" ? local.proactiveFailedRunOccurrences : 1} onChange={(event) => onChange(detector === "persistent_diagnostic" ? { ...local, proactiveDiagnosticCycles: Number(event.target.value) } : { ...local, proactiveFailedRunOccurrences: Number(event.target.value) })} /></label><label>Cooldown minutes <input type="number" min="5" max="1440" value={local.proactiveDetectorCooldownMinutes[detector]} onChange={(event) => setDetectorNumber(detector, "cooldown", Number(event.target.value))} /></label><label>Hourly cap <input type="number" min="1" max="10" value={local.proactiveDetectorMaximumPerHour[detector]} onChange={(event) => setDetectorNumber(detector, "maximum", Number(event.target.value))} /></label><span>Muted signatures: {local.proactiveMutedErrors.length}</span><button disabled={!local.proactiveMutedErrors.length} onClick={() => onChange({ ...local, proactiveMutedErrors: [] })}>Clear muted signatures</button></section>)}</div></details>

    {recommendation && <section className="insight-recommendation"><strong>{recommendation.message}</strong><p>{recommendation.explanation}</p><code>{recommendation.setting}: true → false</code><div><button className="primary" onClick={() => { const next = { ...local, [recommendation.setting]: recommendation.nextValue }; onChange(next); void onSave(next).then(() => setStatus("Recommendation applied by your request.")); }}>Apply Recommendation</button><button onClick={() => { const next = { ...local, proactiveDismissedRecommendations: [...local.proactiveDismissedRecommendations, recommendation.id] }; onChange(next); void onSave(next); }}>Dismiss permanently</button></div></section>}

    <h4>Local metrics</h4>{!local.proactiveMetricsCollection ? <p>Metrics collection is Off. New events are not recorded and stored event metrics are hidden until re-enabled or cleared.</p> : report ? <><div className="insight-metrics"><span><strong>{report.aggregate.eligibleEvents}</strong> eligible events</span><span><strong>{report.aggregate.nudgesShown}</strong> nudges shown</span><span><strong>{report.aggregate.investigate}</strong> Investigate</span><span><strong>{report.aggregate.explain}</strong> Explain</span><span><strong>{report.aggregate.suggestFix}</strong> Suggest Fix</span><span><strong>{report.aggregate.notNow}</strong> Not Now</span><span><strong>{report.aggregate.resolved}</strong> resolved</span><span><strong>{report.aggregate.unresolved}</strong> unresolved</span><span><strong>{percent(report.aggregate.actionRate)}</strong> action rate</span><span><strong>{percent(report.aggregate.dismissalRate)}</strong> dismissal rate</span><span><strong>{percent(report.aggregate.usefulFeedbackRate)}</strong> useful feedback</span><span><strong>{duration(report.aggregate.averageTimeToActionMs)}</strong> average to action</span><span><strong>{duration(report.aggregate.averageTimeToResolutionMs)}</strong> average to resolution</span><span><strong>{report.mutedErrors}/{report.mutedFiles}/{report.mutedProjects}</strong> muted errors/files/projects</span></div><div className="insight-breakdown">{report.byDetector.map((item) => <div key={item.detectorType}><strong>{detectorLabel[item.detectorType]}</strong><span>{item.eligibleEvents} eligible · {item.nudgesShown} shown · {item.resolved} resolved</span><span>Actions {percent(item.actionRate)} · Dismissed {percent(item.dismissalRate)} · Useful {percent(item.usefulFeedbackRate)}</span></div>)}</div></> : <p>Loading local insights…</p>}

    <h4>FYP Evaluation Mode</h4>{report?.activeSession ? <section className="evaluation-active"><strong>Evaluation session active</strong><p>Participant: {report.activeSession.participantId} · Preset: {report.activeSession.preset}. Only sanitized event metadata is recorded.</p><button onClick={() => void stopEvaluation()}>Stop Evaluation</button></section> : <section className="evaluation-consent"><p>This supervised testing mode records only detector categories, timestamps, actions, usefulness, resolution, and preset. It never records project code, paths, filenames, prompts, model responses, raw errors, or terminal output.</p><label>Participant pseudonym <input value={participantId} maxLength={32} onChange={(event) => setParticipantId(event.target.value.replace(/[^A-Za-z0-9_-]/g, ""))} /></label><label><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /> I understand and consent to this local evaluation session.</label><button className="primary" disabled={!consent || participantId.length < 3} onClick={() => void startEvaluation()}>Start Evaluation</button></section>}
    {report && <details><summary>Preview all evaluation report data before export</summary><pre>{JSON.stringify({ label: "Proactive Observer evaluation data", ...report }, null, 2)}</pre></details>}
    <div className="settings-actions"><button onClick={() => void exportData("json")}>Export sanitized JSON</button><button onClick={() => void exportData("csv")}>Export sanitized CSV summary</button><button onClick={() => void clearData()}>Clear Observer insights data</button><button onClick={() => void refresh()}>Refresh</button></div>
    <p>This evaluation report describes interaction metadata only. It is not proof that Observer caused a resolution, improved productivity, or produced an accurate answer.</p>{status && <p className="settings-message" role="status">{status}</p>}
  </div>;
}
