const assert = require('node:assert/strict');
module.exports = async (win, js, wait) => {
 const click = label => js(`Array.from(document.querySelectorAll('button')).find(b => b.textContent === ${JSON.stringify(label)}).click()`);
 const input = (label, value) => js(`{ const e=document.querySelector('[aria-label="${label}"]'); Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(e,${JSON.stringify(value)}); e.dispatchEvent(new Event('input',{bubbles:true})); }`);
 await wait('Boolean(document.querySelector(\'[aria-label="Explanation guidance"]\'))');
 await input('Explanation guidance','Explain for a beginner'); await click('Ask Observer');
 await wait('Boolean(document.querySelector(\'[aria-labelledby="context-preview-title"]\'))');
 assert.equal(await js('window.fixture.calls.length'),0);
 assert.match(await js('document.querySelector(".context-preview").textContent'), /Explain for a beginner/);
 await click('Send to Observer'); await wait('Boolean(document.querySelector(\'[aria-label="Observer answer"] strong\'))');
 assert.equal(await js('window.fixture.calls.length'),1);
 assert.equal(await js('Array.from(document.querySelectorAll(".observer-controls select")).every(e=>e.disabled)'),true);
 assert.equal(await js('document.querySelectorAll(".explanation-messages script,.explanation-messages img,.explanation-messages a").length'),0);
 assert.equal(await js('Boolean(window.unsafe)'),false);
 assert.match(await js('document.querySelector(".explanation-messages pre code").textContent'), /add\(2, 3\)/);
 await js('document.querySelector(".explanation-messages pre").scrollIntoView({block:"center"})');
 require('node:fs').writeFileSync('/tmp/explanation-ui.png', (await win.capturePage()).toPNG());
 await click('Copy answer'); await wait('window.fixture.summary().copied.includes("Adds inputs")');
 await input('Follow-up question','What if a is a string?'); await click('Ask follow-up');
 await wait('document.querySelectorAll(\'[aria-label="Observer answer"]\').length === 2');
 assert.equal(await js('window.fixture.calls[1].explanation.messages.length'),2);
 assert.equal(await js('JSON.stringify(window.fixture.calls[0].contextPackage)===JSON.stringify(window.fixture.calls[1].contextPackage)'),true);
 await input('Source code','def add(a, b):\n    return str(a) + str(b)');
 await wait('document.querySelector(".explanation-conversation").textContent.includes("older source snapshot")');
 await click('Refresh through context preview'); await wait('Boolean(document.querySelector(".context-preview"))');
 assert.equal(await js('window.fixture.calls.length'),2);
 await click('Send to Observer'); await wait('Boolean(document.querySelector(\'[aria-label="Observer answer"]\'))');
 assert.match(await js('window.fixture.calls[2].contextPackage.items[1].content'), /str\(a\)/);
 for(let n=0;n<5;n++){ await input('Follow-up question',`Question ${n}`);await click('Ask follow-up'); await wait(`window.fixture.calls.length === ${n+4} && !document.querySelector('.explanation-conversation').textContent.includes('Waiting for the provider')`); }
 assert.match(await js('document.querySelector(".explanation-conversation").textContent'),/older messages omitted/);
 await js('window.fixture.delay()'); await input('Follow-up question','Slow question'); await click('Ask follow-up');
 await wait('document.querySelector(".explanation-conversation").textContent.includes("Waiting for the provider")');
 assert.equal(await js('Array.from(document.querySelectorAll("button")).find(b=>b.textContent==="Ask follow-up").disabled'),true);
 await click('Cancel request'); assert.equal(await js('window.fixture.summary().aborted'),true);
 const count=await js('document.querySelectorAll(\'[aria-label="Observer answer"]\').length');
 await js('window.fixture.release()'); await new Promise(r=>setTimeout(r,100));
 assert.equal(await js('document.querySelectorAll(\'[aria-label="Observer answer"]\').length'),count);
 await js('window.fixture.deny()'); await click('Ask follow-up'); await wait('Boolean(document.querySelector(".explanation-conversation [role=alert]"))');
 assert.match(await js('document.querySelector(".explanation-conversation [role=alert]").textContent'), /Privacy/);
 await click('New explanation / Clear conversation'); await wait('!document.querySelector(".explanation-conversation")');
 await js('window.fixture.allow(); window.fixture.delay()');
 await click('Ask Observer'); await click('Send to Observer'); await wait('document.querySelector(".explanation-conversation").textContent.includes("Waiting for the provider")');
 await click('New explanation / Clear conversation'); await js('window.fixture.release()');
 await new Promise(r=>setTimeout(r,100)); assert.equal(await js('Boolean(document.querySelector(".explanation-conversation"))'),false);
 await js('window.fixture.delay()'); await click('Ask Observer'); await click('Send to Observer'); await wait('document.querySelector(".explanation-conversation").textContent.includes("Waiting for the provider")');
 await click('Switch project'); await wait('!document.querySelector(".explanation-conversation")');
 await js('window.fixture.release()'); await new Promise(r=>setTimeout(r,100));
 assert.equal(await js('Boolean(document.querySelector(".explanation-conversation"))'),false);
 console.log('PASS Explain renderer: guidance, preview/no early send, safe Markdown, code fences, copy, followups/original snapshot, changed-source label, explicit refresh, bounded history, cancellation, privacy errors, clear/project reset');
};
