import type { ChromeSelectedTextContext } from "./web-context.ts";

const BRIDGE_ORIGIN_PERMISSION = "http://127.0.0.1/*", PORT = 32145 as const, LOCAL_KEY = "proactiveDesktopPairing", PROTOCOL_VERSION = 1 as const;
interface PairingSession { token: string; port: number; protocolVersion: 1 }
export type ConnectionState = "connected" | "desktop_closed" | "not_paired" | "pairing_expired";
export interface BridgeStatus { paired: boolean; state: ConnectionState; message: string }
export interface SendResult { ok: boolean; message: string; recoverable?: boolean; redacted?: boolean; truncated?: boolean }
const validSession = (value: unknown): PairingSession | null => { const item = value as Partial<PairingSession> | null; return item && typeof item.token === "string" && /^[A-Za-z0-9_-]{43}$/.test(item.token) && item.port === PORT && item.protocolVersion === 1 ? item as PairingSession : null; };
async function loadSession() { const stored = await chrome.storage.local.get(LOCAL_KEY); const session = validSession(stored[LOCAL_KEY]); if (!session) await chrome.storage.local.remove(LOCAL_KEY); return session; }
const errorMessage: Record<string, string> = { pairing_expired: "Pairing Expired. Start pairing again in IDE Settings.", invalid_pairing_code: "The pairing code is invalid.", pairing_required: "Not Paired. Connect again from the extension.", origin_rejected: "This extension identity is not allowed by the IDE.", protocol_mismatch: "The extension and IDE protocol versions do not match.", invalid_transfer: "The selected-text payload failed validation.", payload_too_large: "The selection is too large.", duplicate_transfer: "This selection was already sent.", transfer_rejected: "The IDE rejected this selection.", review_queue_full: "The IDE review queue is full. Review pending selections, then retry.", rate_limited: "Too many requests. Wait a moment, then retry.", desktop_unavailable: "Open and sign in to the IDE with a workspace first." };
const messageFor = (value: unknown, fallback: string) => errorMessage[String(value)] ?? fallback;
const post = async (path: string, body: unknown, token?: string) => { const controller = new AbortController(), timeout = setTimeout(() => controller.abort(), 2_000); try { const response = await fetch(`http://127.0.0.1:${PORT}${path}`, { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify(body), cache: "no-store", signal: controller.signal }); if (response.headers.get("X-Proactive-Bridge") !== "1") throw new Error("wrong_service"); return response; } finally { clearTimeout(timeout); } };
const body = async (response: Response) => response.json() as Promise<{ ok?: unknown; token?: unknown; protocolVersion?: unknown; error?: unknown; status?: unknown }>;

export async function bridgeStatus(): Promise<BridgeStatus> {
  const session = await loadSession(); if (!session) return { paired: false, state: "not_paired", message: "Not Paired. Start pairing in IDE Settings, then enter its code here." };
  try { const response = await post("/v1/status", { protocolVersion: PROTOCOL_VERSION }, session.token); const value = await body(response); if (response.status === 401) { await chrome.storage.local.remove(LOCAL_KEY); return { paired: false, state: "not_paired", message: messageFor("pairing_required", "Not Paired") }; } if (!response.ok || value.ok !== true || value.protocolVersion !== 1) return { paired: true, state: "desktop_closed", message: messageFor(value.error, "Desktop service is not ready.") }; return { paired: true, state: "connected", message: "Connected" }; } catch { return { paired: true, state: "desktop_closed", message: "Desktop Closed. Open the IDE to reconnect." }; }
}
export async function pairDesktop(code: string): Promise<BridgeStatus> {
  if (!/^\d{8}$/.test(code)) throw new Error("Enter the 8-digit pairing code from IDE Settings.");
  if (!(await chrome.permissions.request({ origins: [BRIDGE_ORIGIN_PERMISSION] }))) throw new Error("Local IDE access was not granted.");
  try { const response = await post("/v1/pair", { code, deviceName: `Chrome on ${navigator.platform || "this device"}`, protocolVersion: PROTOCOL_VERSION }); const value = await body(response); if (!response.ok) { const message = errorMessage[String(value.error)] ?? "Pairing failed."; const error = new Error(message); error.name = String(value.error); throw error; } const session = validSession({ token: value.token, port: PORT, protocolVersion: value.protocolVersion }); if (!session) throw new Error("The IDE returned an invalid pairing response."); await chrome.storage.local.set({ [LOCAL_KEY]: session }); return { paired: true, state: "connected", message: "Connected" }; } catch (error) { if (error instanceof Error && error.name !== "Error") throw error; throw new Error(error instanceof Error && error.message === "wrong_service" ? "Another service is using the IDE port." : "Desktop Closed. Open the IDE, sign in, and open a workspace."); }
}
export async function disconnectDesktop() { const session = await loadSession(); if (session) await post("/v1/disconnect", { protocolVersion: PROTOCOL_VERSION }, session.token).catch(() => undefined); await chrome.storage.local.remove(LOCAL_KEY); return { paired: false, state: "not_paired", message: "Not Paired" } satisfies BridgeStatus; }
export async function sendToDesktop(capture: ChromeSelectedTextContext): Promise<SendResult> {
  const session = await loadSession(); if (!session) return { ok: false, message: messageFor("pairing_required", "Not Paired") };
  const transferId = crypto.randomUUID(), idempotencyKey = capture.contentHash;
  try { const health = await post("/v1/status", { protocolVersion: PROTOCOL_VERSION }, session.token); if (!health.ok) { const value = await body(health); if (health.status === 401) await chrome.storage.local.remove(LOCAL_KEY); return { ok: false, recoverable: health.status >= 500, message: messageFor(value.error, "Desktop service is not ready.") }; } const response = await post("/v1/context", { protocolVersion: PROTOCOL_VERSION, transferId, sentAt: Date.now(), idempotencyKey, context: capture }, session.token); const value = await body(response); if (response.status === 401) await chrome.storage.local.remove(LOCAL_KEY); if (!response.ok || value.ok !== true) return { ok: false, recoverable: [429, 500, 503].includes(response.status), message: messageFor(value.error, "The IDE rejected this selection.") }; return { ok: true, message: "Sent to the IDE review queue. It is not in Context Tray until you choose Add." }; } catch (error) { return { ok: false, recoverable: true, message: error instanceof Error && error.message === "wrong_service" ? "Another service is using the IDE port." : "Desktop Closed. Keep this review open, start the IDE, then Retry." }; }
}
