import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {buildPrompt,parseImproveCode,getSuggestion,type SuggestContext} from '../src/lib/server/providers.ts';
import {buildImproveCodeContext} from '../apps/desktop/src/main/improve-code-context.ts';
import {IMPROVE_CODE_LIMITS} from '../apps/desktop/src/shared/improve-code.ts';
import {fixSelectionRange} from '../apps/desktop/src/shared/fix-code.ts';
const content='function f(x) { const value = x + 1; return value; }';
const hash=createHash('sha256').update(content).digest('hex');
const projectContext=buildImproveCodeContext({mode:'improve_code',kind:'code',activeRelativePath:'main.js',fileName:'main.js',language:'javascript',content,cursorLine:1,cursorColumn:10,maximumTotalCharacters:9000,maximumCharactersPerFile:6000,maximumRelatedFiles:0,exclusions:[],userRequest:'Keep the public API.'});
const ctx:SuggestContext={kind:'code',fileName:'main.js',content,context:{mode:'improve_code'},projectContext,improveCode:{scope:'function',range:fixSelectionRange(content,undefined),goal:'readability',clarifications:[{question:'Preserve API?',answer:'Yes.'}]},editBase:{targetRelativePath:'main.js',originalContentHash:hash,contentLength:content.length,basedOnUnsavedContent:true}};
for(const goal of ['readability','performance']as const){const prompt=buildPrompt({...ctx,improveCode:{...ctx.improveCode!,goal}});for(const pattern of [/ONE coherent worthwhile improvement/,/public interfaces/,/return values/,/error handling/,/side effects/,/UNTRUSTED DATA/,/No worthwhile improvement found/,/one clarification/,/correctness_issue/,/separate explicit Fix Code/,/Never claim a speedup/,/measured results/,/Compilation alone does not/,/EXISTING tests/,/Yes\./])assert.match(prompt,pattern);assert.doesNotMatch(prompt,/explanation \(1-3 sentences\)/);assert.match(prompt,goal==='performance'?/Goal: Performance/:/Readability & maintainability/);}
const base={explanation:'Remove the intermediate local with the same evaluation order.',snippet:'',tradeoffs:'Keeps the public API; requires no captured intermediate variable.',verification:'Check existing input/output tests; no tests or benchmarks executed.',reason:''};
const edit={targetRelativePath:'main.js',originalContentHash:hash,editType:'replace',range:fixSelectionRange(content,'const value = x + 1; return value;'),expectedOriginalText:'const value = x + 1; return value;',replacementText:'return x + 1;'};
for(const value of [{...base,improveOutcome:'improvement',edit},{...base,improveOutcome:'clarification',clarificationQuestion:'Are inputs numeric?'},{...base,improveOutcome:'no_change'},{...base,improveOutcome:'correctness_issue'}])assert.equal(parseImproveCode(JSON.stringify(value),ctx).improveOutcome,value.improveOutcome);
for(const value of [{...base,improveOutcome:'improvement'},{...base,improveOutcome:'no_change',edit},{...base,improveOutcome:'correctness_issue',edit},{...base,improveOutcome:'clarification'},{...base,improveOutcome:'improvement',edit:{...edit,targetRelativePath:'other.js'}},{...base,improveOutcome:'improvement',edit:{...edit,range:{start:{line:1,column:1},end:{line:99,column:1}}}},{...base,improveOutcome:'improvement',edit,tradeoffs:''},{...base,improveOutcome:'no_change',snippet:'execute'}])assert.throws(()=>parseImproveCode(JSON.stringify(value),ctx));
const body=JSON.stringify({...base,improveOutcome:'no_change'});
for(const stop of ['length','MAX_TOKENS','max_tokens'])assert.throws(()=>parseImproveCode(body,ctx,stop),/output limit/);
assert.throws(()=>parseImproveCode('{"explanation":',ctx));
const original=globalThis.fetch;
try{for(const provider of ['openai','gemini','deepseek','anthropic']as const){let sent:Record<string,unknown>={};globalThis.fetch=async(_url,init)=>{sent=JSON.parse(String(init?.body));return Response.json(provider==='gemini'?{candidates:[{finishReason:'STOP',content:{parts:[{text:body}]}}]}:provider==='anthropic'?{stop_reason:'end_turn',content:[{type:'text',text:body}]}:{choices:[{finish_reason:'stop',message:{content:body}}]});};const response=await getSuggestion(provider,'mock-never-sent',ctx);assert.equal(response.improveOutcome,'no_change');assert.equal(provider==='gemini'?(sent.generationConfig as {maxOutputTokens:number}).maxOutputTokens:provider==='openai'?sent.max_completion_tokens:sent.max_tokens,IMPROVE_CODE_LIMITS.outputTokens);}}finally{globalThis.fetch=original;}
assert.match(buildPrompt({...ctx,liveObserver:true}),/NO_SUGGESTION/);assert.match(buildPrompt({...ctx,improveCode:undefined,context:{mode:'continue_code'}}),/1-3 sentences/);
console.log('PASS Improve Code prompts, trade-offs/performance evidence, four outcomes, invalid/edit-boundary rejection, provider budgets and unrelated contracts (mocked fetch; no paid calls)');
