import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {resolveImproveScope} from './improve-scope.ts';
import {buildImproveCodeContext} from './improve-code-context.ts';
import {ImproveCodeSession} from './improve-code-session.ts';
import {ProjectContextEngine} from './project-context.ts';
import {CheckpointStore} from './checkpoint-store.ts';
import {fixSelectionRange} from '../shared/fix-code.ts';
import {offsetForPosition,validateAndBuildProposedEdit} from '../shared/ai-edit.ts';
import {validImproveContext,validImproveSuggestion} from '../shared/improve-code.ts';
import {validateObserverRequest,type ObserverRequest,type ObserverAskResult} from '../shared/observer.ts';
import type {ProjectContextSeed} from '../shared/project-context.ts';
import type {IpcResult} from '../shared/workspace.ts';
const content='// keep unsaved comment\nfunction double(x) { return x + x; }\nconst untouched = 4;\n';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
function seed(overrides:Partial<ProjectContextSeed>={}):ProjectContextSeed{return {mode:'improve_code',kind:'code',activeRelativePath:'main.js',fileName:'main.js',language:'javascript',content,cursorLine:2,cursorColumn:26,exclusions:[],maximumTotalCharacters:9000,maximumCharactersPerFile:6000,maximumRelatedFiles:0,...overrides};}
function request(overrides:Partial<ProjectContextSeed>={}):ObserverRequest{const input=seed(overrides);return {provider:'demo',mode:'improve_code',kind:'code',fileName:input.fileName,language:input.language,source:'cursor',cursorLine:input.cursorLine,cursorColumn:input.cursorColumn,storeHistory:false,editBase:{targetRelativePath:input.activeRelativePath,originalContentHash:hash(input.content),contentLength:input.content.length,basedOnUnsavedContent:true},contextPackage:buildImproveCodeContext(input),improveCode:{...resolveImproveScope(input),goal:input.improveGoal??'readability',clarifications:[]}};}
const outcome=(improveOutcome:'improvement'|'clarification'|'no_change'|'correctness_issue'):IpcResult<ObserverAskResult>=>({ok:true,value:{provider:'demo',suggestion:{improveOutcome,explanation:improveOutcome==='no_change'?'No worthwhile improvement found.':'Evidence-supported mock review.',snippet:'',reason:'Approved snapshot.',tradeoffs:'Assumes numeric input; no measurements were made.',verification:'Check existing tests and input types. Nothing was executed.',...(improveOutcome==='clarification'?{clarificationQuestion:'Are inputs restricted to numbers?'}:{}),...(improveOutcome==='improvement'?{edit:{targetRelativePath:'main.js',originalContentHash:hash(content),editType:'replace',range:fixSelectionRange(content,'x + x'),expectedOriginalText:'x + x',replacementText:'2 * x'}}:{})}}});
function fixture(){let policy={enabled:true,exclusions:[] as string[],maximumCharacters:9000,maximumFileCharacters:6000,includeDiagnostics:true,includeTerminalError:true,confirmCompleteFile:false};let consent=true,confirmations=0;let ask:(r:ObserverRequest,s:AbortSignal)=>Promise<IpcResult<ObserverAskResult>>=async()=>outcome('clarification');const requests:ObserverRequest[]=[],signals:AbortSignal[]=[];const session=new ImproveCodeSession({policy:async()=>policy,confirm:async()=>{confirmations++;return consent;},ask:(r,s)=>{requests.push(r);signals.push(s);return ask(r,s);}});return {session,requests,signals,setPolicy:(p:Partial<typeof policy>)=>{policy={...policy,...p};},setAsk:(v:typeof ask)=>{ask=v;},setConsent:(v:boolean)=>{consent=v;},confirmations:()=>confirmations};}
test('selection wins over function/file approval and preserves exact columns',()=>{const r=request({selectedCode:'x + x',improveFullFile:true});assert.ok(validateObserverRequest(r));assert.equal(r.improveCode!.scope,'selection');assert.equal(r.contextPackage!.items.find(i=>i.type==='selected_code')!.content,'x + x');assert.deepEqual(r.improveCode!.range,fixSelectionRange(content,'x + x'));});
test('current JS function is exact, including braces in strings and nested expressions',()=>{const source='function f(x) { return "}" + (() => x)(); }\nconst outside = 1;';const r=request({content:source,cursorLine:1,cursorColumn:12});assert.equal(r.contextPackage!.items.find(i=>i.type==='selected_code')!.content,source.split('\n')[0]);assert.equal(r.improveCode!.scope,'function');});
test('long functions are never cut at 80 lines; over-budget functions fail closed',()=>{const source='function long() {\n'+'  let x = 1;\n'.repeat(120)+'}';const c=buildImproveCodeContext(seed({content:source,cursorLine:90,cursorColumn:4}));assert.equal(c.items.find(i=>i.type==='selected_code')!.content,source);assert.throws(()=>buildImproveCodeContext(seed({content:source,cursorLine:90,cursorColumn:4,maximumCharactersPerFile:500})),/no code was sent or truncated/);});
test('Python function ends at dedent and does not capture a neighboring function/global literal',()=>{const source='def first(x):\n    return x + x\n"global literal"\ndef next():\n    return 1\n';const input=seed({fileName:'main.py',activeRelativePath:'main.py',language:'python',content:source,cursorLine:2,cursorColumn:8});assert.equal(buildImproveCodeContext(input).items.find(i=>i.type==='selected_code')!.content,'def first(x):\n    return x + x');assert.throws(()=>resolveImproveScope({...input,cursorLine:3}),/No current function/);});
test('ambiguous syntax/language requires selection or explicit file approval',()=>{for(const source of ['const x = 1;','function broken( {','def f():\n    """complex docstring"""\n    return 1']){const input=seed({content:source,cursorLine:1,cursorColumn:1});assert.throws(()=>resolveImproveScope(input),/Select code.*explicitly approve/);assert.equal(resolveImproveScope({...input,improveFullFile:true}).scope,'file');}assert.throws(()=>resolveImproveScope(seed({fileName:'main.java'})),/No current function/);});
test('goals are explicit and no-change/clarification/bug outcomes are distinct and edit-free',async()=>{for(const goal of ['readability','performance']as const){for(const state of ['no_change','clarification','correctness_issue']as const){const f=fixture();f.setAsk(async()=>outcome(state));const r=await f.session.start('one',request({improveGoal:goal}),content);assert.ok(r.ok);assert.equal(r.value.suggestion.improveOutcome,state);assert.equal(r.value.suggestion.fixOutcome,undefined);assert.equal(r.value.suggestion.edit,undefined);assert.equal(f.requests[0].mode,'improve_code');assert.equal(f.requests[0].fixCode,undefined);assert.equal(f.requests[0].improveCode!.goal,goal);assert.equal(f.requests[0].storeHistory,false);}}assert.equal(validImproveContext({...request().improveCode,goal:'invented'}),false);});
test('clarification reuses approved context, goal and bounded history',async()=>{const f=fixture(),r=request({userRequest:'Keep the public API.'});await f.session.start('one',r,content);for(let n=0;n<4;n++)assert.equal((await f.session.send('one','Numbers only.',hash(content))).ok,true);assert.equal((await f.session.send('one','More',hash(content))).ok,false);assert.deepEqual(f.requests.at(-1)!.contextPackage,r.contextPackage);assert.equal(f.requests.at(-1)!.improveCode!.clarifications.length,4);});
for(const change of [{enabled:false},{exclusions:['main.js']},{maximumCharacters:10},{maximumFileCharacters:1},{confirmCompleteFile:true}])test(`follow-ups honor privacy ${JSON.stringify(change)}`,async()=>{const f=fixture();await f.session.start('one',request(),content);f.setPolicy(change);assert.equal((await f.session.send('one','Numbers',hash(content))).ok,false);assert.equal(f.requests.length,1);});
test('secret code/answers and stale source are rejected; complete-file consent is explicit',async()=>{assert.throws(()=>buildImproveCodeContext(seed({selectedCode:'const password="fixture-sensitive-value"',content:'const password="fixture-sensitive-value"'})),/secrets/);const f=fixture();f.setPolicy({confirmCompleteFile:true});f.setConsent(false);assert.equal((await f.session.start('one',request({improveFullFile:true}),content)).ok,false);assert.equal(f.requests.length,0);f.setConsent(true);await f.session.start('two',request(),content);assert.equal((await f.session.send('two','password="fixture-sensitive-value"',hash(content))).ok,false);assert.equal((await f.session.send('two','Numbers',hash('new'))).ok,false);});
test('cancel/clear rejects late results, prevents duplicates, and permits a fresh session',async()=>{const f=fixture();let release!:(r:IpcResult<ObserverAskResult>)=>void;f.setAsk(async()=>new Promise(r=>{release=r;}));const pending=f.session.start('one',request(),content);await Promise.resolve();await Promise.resolve();assert.equal((await f.session.start('two',request(),content)).ok,false);f.session.clear();assert.equal(f.signals[0].aborted,true);f.setAsk(async()=>outcome('no_change'));assert.equal((await f.session.start('new',request(),content)).ok,true);release(outcome('improvement'));assert.equal((await pending).ok,false);assert.equal((await f.session.send('one','Old project',hash(content))).ok,false);});
for(const fault of ['outside','text','hash','file','bug-edit','missing-tradeoffs']as const)test(`invalid improvement rejected: ${fault}`,async()=>{const f=fixture(),a=outcome('improvement');assert.ok(a.ok);const e=a.value.suggestion.edit!;if(fault==='outside')e.range=fixSelectionRange(content,'untouched');if(fault==='text')e.expectedOriginalText='wrong';if(fault==='hash')e.originalContentHash=hash('old');if(fault==='file')e.targetRelativePath='other.js';if(fault==='bug-edit')a.value.suggestion.improveOutcome='correctness_issue';if(fault==='missing-tradeoffs')a.value.suggestion.tradeoffs='';f.setAsk(async()=>a);assert.equal((await f.session.start('one',request(),content)).ok,false);});
test('validated improvement preserves other unsaved text and checkpoint Undo refuses newer edits',async()=>{const f=fixture();f.setAsk(async()=>outcome('improvement'));const r=await f.session.start('one',request(),content);assert.ok(r.ok);const v=validateAndBuildProposedEdit(r.value.suggestion.edit,r.value.request.editBase!,content,hash(content));assert.ok(v.ok);assert.equal(v.value.proposedContent,content.replace('x + x','2 * x'));const dir=await mkdtemp(join(tmpdir(),'improve-undo-'));try{const store=new CheckpointStore(dir);await store.create({workspaceId:hash('project'),relativePath:'main.js',previousContent:content,previousContentHash:hash(content),appliedContentHash:hash(v.value.proposedContent)},20);await assert.rejects(()=>store.restore(hash('project'),'main.js',hash('newer')),/changed after/);assert.equal((await store.restore(hash('project'),'main.js',hash(v.value.proposedContent))).previousContent,content);}finally{await rm(dir,{recursive:true,force:true});}});
test('read-only configuration is previewed, bounded, removable and rechecked against exclusions',async()=>{const dir=await mkdtemp(join(tmpdir(),'improve-config-'));try{await writeFile(join(dir,'main.js'),content);await writeFile(join(dir,'package.json'),'{"scripts":{"test":"node --test"}}');const engine=new ProjectContextEngine();engine.setWorkspace(dir);const r=request();r.contextPackage=await engine.build(seed({maximumRelatedFiles:2}));assert.equal(r.contextPackage.items.find(i=>i.type==='project_rule')!.source.relativePath,'package.json');const f=fixture();await f.session.start('one',r,content);f.setPolicy({exclusions:['package.json']});assert.equal((await f.session.send('one','Numbers',hash(content))).ok,false);assert.equal(f.requests.length,1);await writeFile(join(dir,'package.json'),'x'.repeat(2100));const bounded=await engine.build(seed({maximumRelatedFiles:2}));assert.ok(bounded.omitted.some(i=>/package.json/.test(i.reason)));assert.equal(bounded.items.some(i=>i.truncated),false);}finally{await rm(dir,{recursive:true,force:true});}});
test('scope cannot be relabeled to include unrelated text',async()=>{const f=fixture(),r=request();r.improveCode!.range=fixSelectionRange(content,undefined);assert.equal((await f.session.start('one',r,content)).ok,false);const noChange=outcome('no_change');assert.ok(noChange.ok);assert.equal(validImproveSuggestion({...noChange.value.suggestion,snippet:'code'}),false);assert.equal(offsetForPosition(content,request().improveCode!.range.end)!<content.length,true);});
test('a rejected new scope cannot reuse an older clarification session with different context',async()=>{
 const f=fixture();await f.session.start('old',request(),content);
 const invalid=request();invalid.improveCode!.range=fixSelectionRange(content,undefined);
 assert.equal((await f.session.start('new',invalid,content)).ok,false);
 assert.equal((await f.session.send('old','Numbers only.',hash(content))).ok,false);
 assert.equal(f.requests.length,1);
});
